DROP DATABASE IF EXISTS employee_trackerDB;
CREATE DATABASE employee_trackerDB;
USE employee_trackerDB;
CREATE TABLE department(
id INT AUTO_INCREMENT NOT NULL,
deptName VARCHAR(30) NOT NULL,
PRIMARY KEY(id)
);
CREATE TABLE employee(
id INT AUTO_INCREMENT NOT NULL,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30),
role_id INT NOT NULL,
manager_id INT NULL,
PRIMARY KEY(id)
);
CREATE TABLE role(
id INT AUTO_INCREMENT NOT NULL,
tite VARCHAR(30),
salary DECIMAL(10,2),
department_id INT NOT NULL,
PRIMARY KEY(id)
);